Addresses #4183, provide OS SDK/API support for the EnergyPlus "CoilSystem:IntegratedHeatPump:AirSource" object
NREL/OpenStudio pull request #4236
Opened 2021-03-08 22:28 UTC by joseph-robertson

Pull request overview
---------------------

 - Fixes #4183

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2021-03-11 11:30 UTC, jmarrec commented on resources/model/OpenStudio.idd
> +  N6,  \field Rated Evaporator Air Flow Rate
I'd have made this one and the other autocalculatable fields `\required-field`. But your API is correct at least

```c++
    boost::optional<double> ratedEvaporatorAirFlowRate() const;

    bool isRatedEvaporatorAirFlowRateAutocalculated() const;

    bool setRatedEvaporatorAirFlowRate(double ratedEvaporatorAirFlowRate);

    void autocalculateRatedEvaporatorAirFlowRate();
```

2021-03-24 09:23 UTC, jmarrec requested changes
Almost perfect. Couple of minor changes requested (I'll make most of them and clean up my review comments) and a bit more testing would be nice.

2021-03-24 09:23 UTC, jmarrec commented on src/model/ScheduleTypeRegistry.cpp
> +      {"CoilWaterHeatingAirToWaterHeatPumpVariableSpeed", "Grid Signal", "gridSignalSchedule", true, "", OptionalDouble(), OptionalDouble()},
@joseph-robertson What is this? I can't find it anywhere in the IDD nor as a method.

2021-03-24 09:23 UTC, jmarrec commented on src/model/test/AirLoopHVACUnitaryHeatPumpAirToAir_GTest.cpp
> +
I haven't seen the coilSystem.containingHVACComponent() method tested neither in this file nor in the src/model/test/CoilSystemIntegratedHeatPumpAirSource_GTest.cpp ?

2021-03-24 09:23 UTC, jmarrec commented on src/model/test/CoilWaterHeatingAirToWaterHeatPumpVariableSpeedSpeedData_GTest.cpp
> +      exit(0);
Add actual testing for this class please

2021-03-24 09:23 UTC, jmarrec commented on src/model/test/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed_GTest.cpp
> +}
Please also test what happens to the SpeedDataList and the SpeedDatas themselves when cloning / removing.

2021-03-24 09:23 UTC, jmarrec commented on src/model/test/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed_GTest.cpp
> +      CoilWaterHeatingAirToWaterHeatPumpVariableSpeed coil(m);
I would like to see tests about adding it to the types that accept it (which according to IDD should be both CoilSystemIntegrated AND directly onto HeatPumpWaterHeater(PumpedCondenser)) and the containingHVACComponent() stuff somewhere (either in parent or child).

2021-03-24 09:24 UTC, jmarrec commented on src/energyplus/ForwardTranslator/ForwardTranslateCoilWaterHeatingAirToWaterHeatPumpVariableSpeed.cpp
> +      // TODO: if it has zero speed data, Log and don't translate
Done 3e0150349d7b14c103df02ac44b88a2737d58448

2021-03-24 09:25 UTC, jmarrec commented on src/model/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed.cpp
> +        // TODO
Done 503a590336396c083b89399830f284ad0188b71f

2021-03-24 09:26 UTC, jmarrec commented on src/model/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed.cpp
> +    }
Done 503a590336396c083b89399830f284ad0188b71f

2021-03-24 09:27 UTC, jmarrec commented on src/model/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed.cpp
> +    }
I added an actual "// TODO" explaining why. I tried to locate it in the source code of E+ but I don't think it actually reports it anywhere.

2021-03-24 09:32 UTC, jmarrec commented on src/model/CoilSystemIntegratedHeatPumpAirSource.cpp
> +    }
| Type                                                  | Reference                               |
|-------------------------------------------------------|-----------------------------------------|
| OS:CoilSystem:IntegratedHeatPump:AirSource            | IntegratedHeatPumps                     |
| OS:Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed | HeatPumpWaterHeaterDXCoilsVariableSpeed |


OS:WaterHeaterHeatPump, field DX Coil references either `IntegratedHeatPumps` or directly the `HeatPumpWaterHeaterDXCoilsVariableSpeed` (I don't know if that makes sense or not)


```
OS:WaterHeaterHeatPump
  [...]
  A12, \field DX Coil
       \required-field
       \type object-list
       \object-list HeatPumpWaterHeaterDXCoils
       \object-list HeatPumpWaterHeaterDXCoilsVariableSpeed
       \object-list IntegratedHeatPumps
```

2021-03-24 09:56 UTC, jmarrec commented on src/model/CoilSystemIntegratedHeatPumpAirSource.cpp
> +    }
```ruby
m = Model.new
hpwh = WaterHeaterHeatPump.new(m)
ci = CoilSystemIntegratedHeatPumpAirSource.new(m)
hpwh.setDXCoil(ci)
=> true

ci.containingHVACComponent.empty?
=> true
```

2021-03-24 10:35 UTC, jmarrec commented on src/model/test/CoilWaterHeatingAirToWaterHeatPumpVariableSpeedSpeedData_GTest.cpp
> +      exit(0);
Done in 0091ee313fee5e1702b700eed04ffe1535581a0d

2021-03-24 10:35 UTC, jmarrec commented on src/model/ScheduleTypeRegistry.cpp
> +      {"CoilWaterHeatingAirToWaterHeatPumpVariableSpeed", "Grid Signal", "gridSignalSchedule", true, "", OptionalDouble(), OptionalDouble()},
Removed in 1ca23846362495dc84903eb821a16b0b645baec6

2021-03-24 10:35 UTC, jmarrec commented on src/model/test/AirLoopHVACUnitaryHeatPumpAirToAir_GTest.cpp
> +
DOne in 7c9bcdcbc98b2529d22c637207d746ec3ca5becd

2021-03-24 10:36 UTC, jmarrec commented on src/model/CoilSystemIntegratedHeatPumpAirSource.cpp
> +    }
Now supported in 12e1a52c08b88dda279dd6bfeb3db5e093a7521f and tested for in 7c9bcdcbc98b2529d22c637207d746ec3ca5becd

2021-03-24 10:40 UTC, jmarrec commented on src/model/test/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed_GTest.cpp
> +      CoilWaterHeatingAirToWaterHeatPumpVariableSpeed coil(m);
Done in 501a283ae2c0eea888c040c0e749fb6c0a8a349a

2021-03-24 10:47 UTC, jmarrec commented on src/model/test/CoilWaterHeatingAirToWaterHeatPumpVariableSpeed_GTest.cpp
> +}
Done in f0409908eeb8aa66a715847f96a9b0f6f298e25c

2021-03-24 10:48 UTC, jmarrec approved these changes
@joseph-robertson I made all changes I wanted to see. Please review to make sure I didn't miss anything or did something stupid. Tested that the OS-res test still passes (https://github.com/NREL/OpenStudio-resources/pull/136)

2021-03-24 14:44 UTC, joseph-robertson commented
@jmarrec, great review. And thanks for punching out all of the items, and for checking the test on OS-res.

2021-03-25 15:30 UTC, merged