Issue 4387 gl tf
NREL/OpenStudio pull request #4520
Opened 2022-01-21 10:22 UTC by Brijendra21

Pull request overview
---------------------

Enhancement : OpenStudio could export a web standard GLTF

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2022-01-25 08:13 UTC, Brijendra21 commented on src/utilities/core/Enum.hpp
>    OPENSTUDIO_ENUM_BUILD_STRINGS_PART(_enum_name :: BOOST_PP_SEQ_ELEM(0, _elem), _elem, 1)
I'm assuming Clang introduced that change..

2022-01-25 08:14 UTC, Brijendra21 commented on src/model/test/GltfForwardTranslator_GTest.cpp
> +*  OpenStudio(R), Copyright (c) 2008-2021, Alliance for Sustainable Energy, LLC, and other contributors. All rights reserved.
Done

2022-01-25 08:14 UTC, Brijendra21 commented on src/model/test/GltfForwardTranslator_GTest.cpp
> +//#include "../tiny_gltf.h"
Done

2022-01-25 08:16 UTC, Brijendra21 commented on src/model/test/GltfForwardTranslator_GTest.cpp
> +/// <summary>
Removed /// visual studio type comments and comment tags to plain and simple //.
Looking into the latter part...

2022-01-25 08:17 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.hpp
> +#endif  //MODEL_GLTFFORWARDTRANSLATOR_HPP
Added..

2022-01-25 08:17 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.hpp
> +*  OpenStudio(R), Copyright (c) 2008-2021, Alliance for Sustainable Energy, LLC, and other contributors. All rights reserved.
Done..

2022-01-25 08:18 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.cpp
> +*  OpenStudio(R), Copyright (c) 2008-2021, Alliance for Sustainable Energy, LLC, and other contributors. All rights reserved.
Done

2022-01-25 08:18 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.cpp
> +  /// <summary>
took care of it..

2022-01-25 08:19 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.cpp
> +  GLTF::Material CreateMaterial(const std::string& name, float red, float green, float blue, float alpha, bool isDoubleSided) {
done.

2022-01-25 08:19 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.cpp
> +    //result.push_back({"Floor", 128, 128, 128, 1, true});
done

2022-01-25 14:24 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.hpp
> +    bool CreateTriangleGLTF(const path& outputPath);
made changes accordingly.

2022-01-25 14:27 UTC, Brijendra21 commented on src/model/test/GltfForwardTranslator_GTest.cpp
> +/// <summary>
C++ gltf validator's status is still experimental (W.I.P). Almost every rendering platform provides the validation results as soon as we try rendering a gltf so I think this isn't an issue.

2022-01-26 17:21 UTC, jmarrec requested changes
There are portion of the code that I'm not qualified/smart enough to fully understand but there are a few C++ improvements and code smell I'm seeing.

As this is a rather big amount of review comments, I'll going to a make a PR with some refactoring of this, and I'll let you take a look at it before you merge (partially or fully) into this branch.

2022-01-26 17:21 UTC, jmarrec commented on src/model/GltfForwardTranslator.cpp
> +    float divider = 1;
What's the point of this divider = 1?

2022-01-28 17:59 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.cpp
> +  int addIndices(std::vector<size_t>& faceIndices, std::vector<unsigned char>& _indicesBuffer, std::vector<GLTF::Accessor>& _accessors) {
// Adds & Creates Face Indices buffers and Accessors
  // This method infers the indicesbuffer and adds them to the glTF model accessor
  // which expects two types of accessor input one from indicesbuffer and the second
  // one form coordinates buffer. So here after appending the buffer content it is sending
  // over the index so the containing node will be aware of which one to refer.
  // A better overview here at [Infographic  ](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/figures/gltfOverview-2.0.0b.png)
  // param : faceIndices
  // param : _indicesBuffer
  // param : _accessors
  // returns : index of the Face Indices

2022-01-28 18:03 UTC, Brijendra21 commented on src/model/GltfForwardTranslator.cpp
> +    gltf_Model.nodes = _nodesNew;
if I'm changing then top node is not set properly and rendered orientation isn't correct.
![image](https://user-images.githubusercontent.com/78803858/151598316-34322156-3c3b-4ace-b1c0-1b7de71fb33f.png)

Originally 
![image](https://user-images.githubusercontent.com/78803858/151598478-39747802-3b1b-407a-9fa5-9f70d28a906f.png)

2022-01-31 08:44 UTC, jmarrec commented on src/model/GltfForwardTranslator.cpp
> +    gltf_Model.nodes = _nodesNew;
@Brijendra21 Couple of things then:
* This isn't captured in unit tests and probably should (all tests were passing locally when I made my changes)
* we should identify why and correct it, it's probably just a small hiccup. It's a waste to have to create a new vector and push back all elements into it. Just ensure topNode is the first one to begin with.

2022-03-08 21:24 UTC, merged