FloorspaceJS to OpenStudio reverse translator. FIrst implementation p…
NREL/OpenStudio pull request #4623
Opened 2022-07-01 20:07 UTC by ggartside

…assing unit tests.

Pull request overview
---------------------

 - Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2022-07-01 20:31 UTC, ggartside commented
This is a floorspace to osm reverse translator. It consists of two distinct modules, a module to to deserialize the floorspace json file into memory and a module to convert the floorspace model into an osm model.

The floorspace module comprises a set of classes that each represent concepts in the floorspace model and the structure of the floorspace model. These classes also implement the visitor design pattern via `Accept `- `Dispatch `methods as defined in the visitor interface, `FSDispatchable`.

The reverse translator is implemented in two parts, a public facing class implements the main API method, `modelFromFloorspace`, and a private visitor class that is implemented solely in the cpp file. Each Dispatch method in the visitor is used where appropriate to create the OSM objects form the floorspace objects.

For example the `Dispatch `method for `FSStory` calls the `Accept` method on all the spaces, the `FSSpace` `Dispatch` method Creates the OpenStudio Space and the surfaces and sub-surfaces and similarly for all the building shading elements too.

2022-07-05 11:21 UTC, jmarrec requested changes
I haven't done an in-depth review of the actual functionality yet. But there are issues in the design IMHO. I have made some of changes as I went through the review and pushed to this branch but there are more to address.

The core question I have if whether the visitor pattern is really needed in that case. I may be missing the larger/long term picture here, but currently it seems to bring complexity for no benefit since there's no actual double dispatching happening. Interface classes may be enough and simpler.

----

@ggartside I've started to resolve some of the comments myself because I pushed some fixes in order to remove some clobber, but you should expand and read them anyways (some you may disagree with). Thanks!

2022-07-05 11:21 UTC, jmarrec commented on src/utilities/floorspace/FSModel.hpp
> +class UTILITIES_API FSBase : FSDispatchable
I have done some pragma ignores in 35bf7ba1475724a276f21319a77de3a88b2be558 for the time being, but this needs to be addressed / justified.

2022-07-05 11:22 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +#include "../geometry/intersection.hpp"
Done in 924972a8a80857e96ce24ca4f2e440637c6bb4b7

2022-07-05 11:22 UTC, jmarrec commented on src/model/FloorspaceReverseTranslator.cpp
> +  class FloorspaceReverseTranslator_Impl : public FSVisitor
done in f570bf50e66cc18c72e2959ad65b1871263e14a3

2022-07-05 11:23 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +}
Done in aa721bf60938f95ed76bf97b1c5b10ce747929d1

2022-07-05 11:23 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +}
Done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:24 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +//
Done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:26 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +#include <iomanip>
Done in e7a48b2c8ab5deb6b459bd4e62c51af11901125b

2022-07-05 11:26 UTC, jmarrec commented on src/utilities/floorspace/FSModel.hpp
> +  const std::vector<FSDoorDefinition> doorDefinitions() const;
Done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:27 UTC, jmarrec commented on src/utilities/floorspace/FSModel.hpp
> +  double northAxis() const;
done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:29 UTC, jmarrec commented on src/utilities/floorspace/FSModel.hpp
> +  double gelowFloorPlenumHeight() const;
Done in 0dc2f6b6810f2abb5f260b686055a000fb5ba36c

2022-07-05 11:29 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +FSFiller::FSFiller(const Json::Value& root, const FSModel& model, FSStory& story) : FSBase(root) {
Done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:29 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +FSShading::FSShading(const Json::Value& root, const FSModel& model, FSStory& story) : FSBase(root) {
Done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:30 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +      }
Done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-05 11:31 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +        m_thermalZones.emplace_back(FSThermalZone(thermalZones[t]));
done in bfa1cc5297cd0349810030d38b2265d1a10e7157

2022-07-28 10:25 UTC, jmarrec commented on src/utilities/floorspace/FSModel.cpp
> +  if (parsingSuccessful) {
`} else {`

2022-07-28 10:25 UTC, jmarrec commented on src/model/test/FloorspaceReverseTranslator_GTest.cpp
> +  double tol = 0.001;  // Same tolerance as defaulyts for circularEqual
```suggestion
  double tol = 0.001;  // Same tolerance as defaults for circularEqual
```

2022-08-08 17:28 UTC, DavidGoldwasser commented
With latest installer, fenestration by WWR seems to work when running the measure unit test from model articulation gem
https://github.com/NREL/openstudio-model-articulation-gem/compare/develop...floorspace_js_translation

![Screen Shot 2022-08-08 at 11 26 37 AM](https://user-images.githubusercontent.com/4857055/183477715-b3b19020-c1c0-46b9-b4ee-2ff9ad0b133f.png)

2022-08-08 17:30 UTC, DavidGoldwasser approved these changes

2022-08-08 20:00 UTC, tijcolem commented
@DavidGoldwasser Thanks for confirming.  This looks good to me. Ignore the CI on the last commit as it was failing due to BCL issues unrelated to the this PR.

2022-08-08 20:00 UTC, merged