Addresses #4615, wrap OutputControl:Table:Style and Output:SQLite
NREL/OpenStudio pull request #4625
Opened 2022-07-19 01:07 UTC by joseph-robertson

Pull request overview
---------------------

 - Fixes #4615
 - Also adds FT tests and RT support for `OutputControlReportingTolerances`

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2022-07-25 13:07 UTC, jmarrec requested changes
This is looking really good. I added a couple of minor suggestions.

2022-07-25 13:07 UTC, jmarrec commented on src/energyplus/ForwardTranslator.cpp
> +    result.push_back(IddObjectType::OS_Output_SQLite);
Add them to the list of objects to always translate, makes sense.

2022-07-25 13:07 UTC, jmarrec commented on src/energyplus/ForwardTranslator.cpp
> +      boost::optional<model::OutputControlTableStyle> _tableStyle = model.getOptionalUniqueModelObject<model::OutputControlTableStyle>();
(No changes needed, but FYI if we end up making our IDD (or Ctor) use the same defaults as the FT, you could just call model.getUniqueModelObject<XXX>() to instantiate the object as we operate on a copy of our model to begin with. This is maybe clearer this way though.)

2022-07-25 13:07 UTC, jmarrec commented on src/energyplus/Test/OutputControlReportingTolerances_GTest.cpp
> +  // Get the unique object
We probably want to first do a translation without the object instantiated, ensure one isn't present in the IDF.

2022-07-25 13:07 UTC, jmarrec commented on src/energyplus/Test/OutputControlTableStyle_GTest.cpp
> +  OutputControlTableStyle outputControlTableStyle = m.getUniqueModelObject<OutputControlTableStyle>();
, make sure we do get the default behavior, also test with setExcludeHTMLOutputReport / setIPTabularOutput as well.

2022-07-25 13:07 UTC, jmarrec commented on src/energyplus/Test/OutputSQLite_GTest.cpp
> +  OutputSQLite outputSQLite = m.getUniqueModelObject<OutputSQLite>();
Test without object instantiated, make sure we do get the default behavior, and test with `ft.setExcludeSQliteOutputReport(bool)` too

2022-07-25 16:58 UTC, joseph-robertson commented on src/energyplus/ForwardTranslator/ForwardTranslateOutputControlTableStyle.cpp
> +    }
Neither does `OutputControlReportingTolerances`... I will remove there, too.

2022-07-25 17:22 UTC, joseph-robertson commented on src/model/OutputSQLite.cpp
> +  }
Hmm it's like this for a bunch of `OutputXXX` objects...

2022-07-25 22:19 UTC, jmarrec commented on src/model/OutputSQLite.cpp
> +  }
Yeah I know. Generateclass.rb does it I think. It's nitpicking anyways

2022-07-26 06:50 UTC, jmarrec approved these changes

2022-07-26 06:50 UTC, jmarrec commented on src/energyplus/Test/OutputControlReportingTolerances_GTest.cpp
> +    ForwardTranslator ft;
(could use the same ft and model).

2022-07-26 09:10 UTC, merged