Remove deprecated methods
NREL/OpenStudio pull request #4632
Opened 2022-07-28 23:02 UTC by joseph-robertson

Pull request overview
---------------------

 - Fixes #4618

Which deprecated methods should be removed?
- [ ] AirConditionerVariableRefrigerantFlow
- [ ] AirLoopHVAC
- [ ] AirTerminalSingleDuctVAVNoReheat
- [ ] AirTerminalSingleDuctVAVReheat
- [ ] AirWallMaterial
- [ ] AvailabilityManagerNightCycle
- [ ] BuildingUnit
- [ ] CoilCoolingDXSingleSpeed
- [ ] CoilCoolingDXTwoSpeed
- [ ] CoilCoolingWater
- [ ] CoilCoolingWaterToAirHeatPumpEquationFit
- [ ] CoilHeatingGas
- [ ] CoilHeatingWaterToAirHeatPumpEquationFit
- [ ] ConstructionAirBoundary
- [ ] CurveDoubleExponentialDecay
- [ ] DesignDay
- [ ] DesignSpecificationOutdoorAir
- [ ] EvaporativeCoolerDirectResearchSpecial
- [ ] ExteriorFuelEquipment
- [ ] ExteriorLights
- [ ] FanConstantVolume
- [ ] FanZoneExhaust
- [ ] GenericModelObject
- [ ] HeatPumpWaterToWaterEquationFitCooling
- [ ] HeatPumpWaterToWaterEquationFitHeating
- [ ] LayeredConstruction
- [ ] Node (methods deprecated for 9+ years)
- [ ] ParentObject
- [ ] PlanarSurface
- [ ] PlantLoop
- [ ] PumpVariableSpeed
- [ ] ScheduleFile
- [ ] SiteWaterMainsTemperature
- [ ] SizingSystem (note about removing after openstudio-standards 0.29 is released)
- [ ] SpaceInfiltrationDesignFlowRate
- [ ] StandardGlazing
- [ ] SubSurface
- [ ] ThermalZone
- [ ] ThermostatSetpointDualSetpoint
- [x] ZoneAirMassFlowConservation (methods deprecated as of OS 1.9.3 that do nothing)
- [ ] ZoneHVACEquipmentList
- [ ] ZoneHVACLowTempRadiantConstFlow
- [ ] ZoneHVACPackagedTerminalAirConditioner
- [ ] ZoneHVACPackagedTerminalHeatPump
- [ ] ZoneHVACTerminalUnitVariableRefrigerantFlow
- [ ] ZoneVentilationDesignFlowRate

### Pull Request Author

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [x] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2022-07-29 16:57 UTC, tijcolem commented
I think we should create a wiki page that describes the policy for deprecated methods. Do we support 2 versions? 1 Version? Use OS_DEPRECATE.  I think the warning should ouput the last supported version.

2022-08-01 23:36 UTC, joseph-robertson commented
@jmarrec If we remove the `AirWallMaterial` class, do we need to create a VT from `Material:AirWall` to `Construction:AirBoundary`? Would it follow the now obsolete code from FT:
```
    // replace old style air wall Constructions with ConstructionAirBoundary
    for (LayeredConstruction construction : model.getModelObjects<LayeredConstruction>()) {
      if (construction.isModelPartition() && (construction.numLayers() == 1)) {
        MaterialVector layers = construction.layers();
        OS_ASSERT(layers.size() == 1u);

        // if this is an old style air wall
        if (layers[0].optionalCast<AirWallMaterial>()) {
          ConstructionAirBoundary newConstruction(model);
          newConstruction.setName(construction.nameString() + "_ConstructionAirBoundary");

          for (WorkspaceObject source : construction.sources()) {
            for (unsigned index : source.getSourceIndices(construction.handle())) {
              bool test = source.setPointer(index, newConstruction.handle());
              OS_ASSERT(test);
            }
          }

          LOG(Warn, "Construction '" << construction.nameString() << "' has been converted to ConstructionAirBoundary '"
                                     << newConstruction.nameString() << "'.");
          construction.remove();
        }
      }
    }
```

2022-08-02 07:51 UTC, jmarrec commented
> @jmarrec If we remove the AirWallMaterial class, do we need to create a VT from Material:AirWall to Construction:AirBoundary? Would it follow the now obsolete code from FT:

Yes, absolutely. Scan constructions, find those that have only one layers that is an Material:AirWall, create a new Construction:AirBoundary, delete/don't VT the original construction and layer.

2022-09-01 12:41 UTC, jmarrec requested changes

2022-09-01 12:41 UTC, jmarrec commented on src/model/PlanarSurface.cpp
> -            }
Remove this entire block. Also need to update comment in hpp

2022-09-01 12:41 UTC, jmarrec commented on src/model/SizingSystem.cpp
> -  }
OpenStudio-resources needs adjustment: I'd want a PR that fixes stuff and confirmation that everything still runs.

this one is disabled but should still be fixed: https://github.com/NREL/OpenStudio-resources/blob/6c90661c95c0e896ac447eefaa153c9205319534/model/simulationtests/afn_single_zone_ac.rb#L56

2022-09-01 12:41 UTC, jmarrec commented on src/model/ZoneAirMassFlowConservation.cpp
> -    }
https://github.com/NREL/OpenStudio-resources/blob/6c90661c95c0e896ac447eefaa153c9205319534/model/simulationtests/zone_mixing.rb#L71

2022-09-01 15:08 UTC, jmarrec commented on src/osversion/VersionTranslator.cpp
> +          for (const IdfExtensibleGroup& eg : object.extensibleGroups()) {
for loop useless if you have 1 extensible group.

2022-09-01 15:36 UTC, jmarrec commented
I fixed the regression tests in https://github.com/NREL/OpenStudio-resources/pull/174

2022-09-01 16:04 UTC, jmarrec commented on src/osversion/VersionTranslator.cpp
> +          for (const IdfExtensibleGroup& eg : object.extensibleGroups()) {
done in 51e36b5220938c78707ef1a4d6d00b1242463b49

2022-09-01 16:04 UTC, jmarrec commented
@joseph-robertson I'll let this one build. Then I'll do another run of https://github.com/NREL/OpenStudio-resources/pull/174 to make sure everything is alright and then we can merge. Thanks for your work!

2022-09-02 08:06 UTC, merged