Addresses #4647, wrap the E+ Table:Lookup, Table:IndependentVariableList, and Table:IndependentVariable objects
NREL/OpenStudio pull request #4652
Opened 2022-08-19 20:08 UTC by joseph-robertson

Pull request overview
---------------------

 - Fixes #4647

### Pull Request Author

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [x] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2022-08-22 20:49 UTC, jmarrec commented
@joseph-robertson, some thoughts:


> **Possible implementation:**
> 
>     * `Table:Lookup` (Curve?)

* Yeah, this one is a Curve (< ResourceObject < ParentObject < ModelObject)

>     * `Table:IndependentVariableList` (Use `ModelObjectList`?)

* ModelObjectList would work yes. But its behavior relating to clone/remove might be annoying (I believe it'll clone the underlying objects, regardless of whether they are ResourceObjects or not, so you might have to work around that... make sure to write extensive tests for that)

>     * `Table:IndependentVariable` (ParentObject?)

* I would say ResourceObject actually. It could technically be shared by several TableLookup objects. 
    * Eg: you have a CSV file (or you use the extensible fields instead of using an external file, doesn't matter conceptually) where the first column is the temperature (independent variable), and the second and third columns are the EIRFT and CAPFT values (dependent variables/output), then you would have two TableLookUp using the same Table:IndependentVariable object.

2022-08-31 12:44 UTC, jmarrec requested changes

2022-08-31 12:45 UTC, jmarrec commented on resources/model/OpenStudio.idd
> +       \retaincase
8ecd2254fd7311223941b834bf3c7dbbf5dd4637 and 8304c9d46265170b6302be4ea97c1dec07a6fd64

2022-08-31 12:45 UTC, jmarrec commented on src/model/TableIndependentVariable.hpp
> +    bool setInterpolationMethod(std::string interpolationMethod);
https://github.com/NREL/OpenStudio/commit/8ecd2254fd7311223941b834bf3c7dbbf5dd4637 and https://github.com/NREL/OpenStudio/commit/8304c9d46265170b6302be4ea97c1dec07a6fd64

2022-08-31 12:45 UTC, jmarrec commented on src/model/TableIndependentVariable.hpp
> +    static IddObjectType iddObjectType();
https://github.com/NREL/OpenStudio/commit/8ecd2254fd7311223941b834bf3c7dbbf5dd4637 and https://github.com/NREL/OpenStudio/commit/8304c9d46265170b6302be4ea97c1dec07a6fd64

2022-08-31 12:46 UTC, jmarrec commented on src/model/test/TableLookup_GTest.cpp
> +TEST_F(ModelFixture, TableLookup) {
tests in a9d87a766dc9ab7adc0879731c498a0f80d8e79e (failing) plus fix in b4255acb4a535bbe74e0b19ec6b723b34c0ecef3

2022-08-31 12:48 UTC, jmarrec commented on src/energyplus/ForwardTranslator/ForwardTranslateTableLookup.cpp
> +    tableLookup.setString(Table_LookupFields::IndependentVariableListName, tableIndependentVariableList.nameString());
Done in 75a179ff0f8f6fdfa6929905b58b5660f4971dbd

2022-08-31 12:48 UTC, jmarrec commented on src/energyplus/ForwardTranslator/ForwardTranslateTableLookup.cpp
> +      IdfObject tableIndependentVariable(IddObjectType::Table_IndependentVariable);
I redid the FT (and broke it in two) in f5d52a79cb97a18c847ad478111cb0e61591879f

2022-08-31 12:49 UTC, jmarrec commented on src/model/TableLookup.hpp
> +    unsigned int numberofOutputValues() const;
Done in dced8f0847bfc5717789b4864ee30cc2a5d0768c and eb66a23d786fe37a80c9e5e1771b3a7863868085

2022-08-31 12:49 UTC, jmarrec commented on src/model/TableLookup.cpp
> +    }
cf 09380daf8743dfcf87baf005cf6374a4dcacf229

2022-08-31 12:49 UTC, jmarrec commented on src/model/TableLookup.cpp
> +    }
cf 09380daf8743dfcf87baf005cf6374a4dcacf229

2022-08-31 12:50 UTC, jmarrec commented
@joseph-robertson I have made a significant amount of changes, could you review that? Still missing VersionTranslation rules and some more changes, cf TODO in https://github.com/NREL/OpenStudio/pull/4652#discussion_r959341446

2022-08-31 15:38 UTC, jmarrec commented on src/energyplus/ForwardTranslator.cpp
> +      TableLookup tableLookup(model);
Added VT tests in f49be2690afe63955c3fa8e0f4abc2fd8630a542 and VT in f796e1cae355203352af4a38332dbdb7175b5b88

2022-08-31 18:26 UTC, jmarrec commented on src/energyplus/ForwardTranslator.cpp
> +      }
```suggestion
      // Name
      tableLookup.setName(tableMulti.nameString());
```

2022-09-01 09:12 UTC, jmarrec commented on src/utilities/core/Deprecated.hpp
> +// clang-format on
New macro for clarity/shortness. See it in example at https://godbolt.org/z/jEKzcedoK across 3 compilers

2022-09-01 11:52 UTC, jmarrec approved these changes
@joseph-robertson I added a ReverseTranslator. I opened a PR to https://github.com/NREL/OpenStudio-resources/pull/173 which caught a few bugs and I added an explicit test for sharing two TableIndependentVariables on two TableLookups.

2022-09-01 11:52 UTC, jmarrec commented on src/energyplus/ReverseTranslator.cpp
> +      }
new RT

2022-09-01 11:52 UTC, jmarrec commented on src/utilities/core/Deprecated.hpp
> +// clang-format on
I removed it, swig was choking on it

2022-09-01 11:53 UTC, jmarrec commented on src/energyplus/ForwardTranslator.cpp
> +      TableLookup tableLookup(model);
Done everything in the latest commits

2022-09-07 21:47 UTC, joseph-robertson commented on src/energyplus/ForwardTranslator/ForwardTranslateTableIndependentVariable.cpp
> +    }
@jmarrec Is this still a TODO?

2022-09-08 08:18 UTC, merged