HeatPump:PlantLoop:EIR:*: new fields
NREL/OpenStudio pull request #4962
Opened 2023-09-06 19:54 UTC by joseph-robertson

Pull request overview
---------------------

- [x] Support new fields for `HeatPump:PlantLoop:EIR:Cooling`:
  - "Control Type"
  - "Flow Mode"
  - "Minimum Part Load Ratio"
  - "Minimum Source Inlet Temperature"
  - "Maximum Source Inlet Temperature"
  - "Minimum Supply Water Temperature Curve Name"
  - "Maximum Supply Water Temperature Curve Name"
- [ ] Support new fields for `HeatPump:PlantLoop:EIR:Heating`:
  - "Heating To Cooling Capacity Sizing Ratio"
  - ...
  - "Timed Empirical Defrost Heat Input Energy Fraction Curve Name"

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

2023-09-07 14:57 UTC, joseph-robertson commented on src/model/HeatPumpPlantLoopEIRCooling.cpp
>      setReferenceCoefficientofPerformance(7.5);  // IDD default
This IDD default has changed to 3.0. Should that be captured here?

2023-09-07 14:57 UTC, joseph-robertson commented on src/model/HeatPumpPlantLoopEIRCooling.cpp
>      setReferenceCoefficientofPerformance(7.5);
Here too.

2023-09-12 13:45 UTC, jmarrec requested changes
Model tests, FT tests, required-field, all good.

Missing a min fields update, and some resetXXXCurve function and this is good to go!

2023-09-12 21:12 UTC, joseph-robertson commented
@jmarrec segfault in tests - presumably related to new reset curve methods. do you see anything obvious?

2023-09-13 08:01 UTC, jmarrec commented on src/model/HeatPumpPlantLoopEIRHeating.cpp
> +  }
Segfault is here @joseph-robertson

2023-09-13 08:34 UTC, merged

2023-09-28 14:50 UTC, jmarrec commented
We forgot VT! cf https://github.com/NREL/OpenStudio/issues/4977